# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cedula', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='cedula: ')),
                ('apellidoPer', models.CharField(max_length=20, verbose_name='apellido ')),
                ('nombrePer', models.CharField(max_length=20, verbose_name='nombre ')),
            ],
        ),
    ]
