# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='imagenPer',
            field=models.ImageField(default=1, upload_to='Photos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellidoPer',
            field=models.CharField(max_length=20, verbose_name='apellidO '),
        ),
        migrations.AlterField(
            model_name='persona',
            name='cedula',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='cedulA: '),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombrePer',
            field=models.CharField(max_length=20, verbose_name='nombrE '),
        ),
    ]
